name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      working-directory: SchoolMS
      run: dotnet restore SchoolMS.sln

    - name: Build (Release)
      working-directory: SchoolMS
      run: dotnet build SchoolMS.sln --configuration Release --no-restore

    - name: Test
      working-directory: SchoolMS
      run: dotnet test SchoolMS.sln --no-build --verbosity normal
figuration Release --no-restore

    - name: Test
      run: dotnet test SchoolMS/SchoolMS.sln --no-build --verbosity normal
