name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'   # change to 6.0.x/7.0.x if needed

    - name: Restore
      run: dotnet restore

    - name: Build (Release)
      run: dotnet build SchoolMS/SchoolMS.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test SchoolMS/SchoolMS.sln --no-build --verbosity normal
